name = "GroupTesting"
uuid = "3d9140b9-2699-468e-abff-6b59d65ee1fd"
authors = ["Olivier Verdier <olivier.verdier@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
GroupTools = "1a3c8808-2843-4c72-af8e-d50ed15039bf"
Manifolds = "1cead3c2-87b3-11e9-0ccd-23c62b72b94e"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[targets]
test = ["Test", "Random"]
